/**
 * 环境配置模块
 * 定义项目常量和环境初始化函数
 */

import path from "path";
import fs from "fs";
import { Logger } from "./logger";
import { Command } from "./cmd";
import { BIN_DIR } from "./const";



/** Lock 文件路径（用于标记环境是否已初始化） */
export const LOCK_FILE: string = path.join(BIN_DIR, ".env.lock");

/** 需要安装的 Go 工具列表 */
export const GO_TOOLS: Array<{ name: string; pkg: string }> = [
  { name: "kratos", pkg: "github.com/go-kratos/kratos/cmd/kratos/v2@latest" },
  { name: "buf", pkg: "github.com/bufbuild/buf/cmd/buf@latest" },
  { name: "air", pkg: "github.com/air-verse/air@latest" },
  { name: "wire", pkg: "github.com/google/wire/cmd/wire@latest" },
  { name: "protoc-gen-go", pkg: "google.golang.org/protobuf/cmd/protoc-gen-go@latest" },
  { name: "protoc-gen-go-enums", pkg: "github.com/utilitywarehouse/protoc-gen-go-enums@latest" },
  { name: "protoc-gen-go-grpc", pkg: "google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest" },
  { name: "protoc-gen-go-http", pkg: "github.com/go-kratos/kratos/cmd/protoc-gen-go-http/v2@latest" },
  { name: "protoc-gen-go-errors", pkg: "github.com/go-kratos/kratos/cmd/protoc-gen-go-errors/v2@latest" },
  { name: "protoc-gen-typescript-http", pkg: "github.com/edwinhuish/protoc-gen-typescript-http@latest" },
  { name: "protoc-gen-openapi", pkg: "github.com/google/gnostic/cmd/protoc-gen-openapi@latest" },
  { name: "golangci-lint", pkg: "github.com/golangci/golangci-lint/cmd/golangci-lint@latest" },
];

const defaultLogger = new Logger("env");

/**
 * 检查是否存在 lock 文件
 */
export function hasLockFile(): boolean {

  if(!fs.existsSync(BIN_DIR)) {
    fs.mkdirSync(BIN_DIR, { recursive: true });
  }

  return fs.existsSync(LOCK_FILE);
}

/** Lock 文件中标记安装完成的行 */
const LOCK_COMPLETED_MARKER = "COMPLETED";

/** 等待其他进程完成安装的轮询间隔 (ms) */
const WAIT_INTERVAL = 2000;

/** 等待其他进程完成安装的超时时间 (ms) */
const WAIT_TIMEOUT = 5 * 60 * 1000;

/**
 * 尝试原子地创建 lock 文件（标记为"安装中"状态）
 * 使用 O_EXCL | O_CREAT 确保只有一个进程能成功创建
 * @returns true 表示当前进程成功创建（即获得了锁），false 表示文件已存在
 */
function tryCreateLockFile(): boolean {
  try {
    const fd = fs.openSync(LOCK_FILE, fs.constants.O_CREAT | fs.constants.O_EXCL | fs.constants.O_WRONLY);
    fs.writeSync(fd, `# Auto-generated by initEnv\n# Created: ${new Date().toISOString()}\n# Status: pending\n`);
    fs.closeSync(fd);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "EEXIST") {
      return false;
    }
    throw error;
  }
}

/**
 * 将 lock 文件标记为"安装完成"状态
 */
function completeLockFile(): void {
  fs.appendFileSync(LOCK_FILE, `# Status: ${LOCK_COMPLETED_MARKER}\n`);
}

/**
 * 检查 lock 文件是否已标记为安装完成
 */
function isLockFileCompleted(): boolean {
  try {
    const content = fs.readFileSync(LOCK_FILE, "utf-8");
    return content.includes(`Status: ${LOCK_COMPLETED_MARKER}`);
  } catch {
    return false;
  }
}

/**
 * 等待指定毫秒数
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * 等待其他进程完成环境安装
 * 轮询 lock 文件直到状态变为 completed 或超时
 * 超时后删除 stale lock 文件，由当前进程接手安装
 */
async function waitForCompletion(logger: Logger): Promise<void> {
  logger.info("等待其他进程完成环境安装...");

  const start = Date.now();

  while (Date.now() - start < WAIT_TIMEOUT) {
    // lock 文件被删除（其他进程安装失败），当前进程可以重试
    if (!fs.existsSync(LOCK_FILE)) {
      logger.info("其他进程安装失败，由当前进程接手");
      return;
    }

    if (isLockFileCompleted()) {
      logger.success("其他进程已完成环境安装");
      return;
    }

    await sleep(WAIT_INTERVAL);
  }

  // 超时：其他进程可能已崩溃，删除 stale lock 文件
  logger.warn(`等待超时 (${WAIT_TIMEOUT / 1000}s)，删除过期 lock 文件`);
  removeLockFile();
}

/**
 * 删除 lock 文件（用于强制重新初始化）
 */
export function removeLockFile(): void {
  if (fs.existsSync(LOCK_FILE)) {
    fs.unlinkSync(LOCK_FILE);
  }
}

/**
 * 初始化开发环境
 * 安装所有必要的 Go 工具到 bin 目录
 * 如果存在 lock 文件则跳过安装
 */
export async function initEnv(logger = defaultLogger): Promise<void> {

  const cmd = new Command(logger);

  // 原子检查：如果 lock 文件已存在且已完成，说明环境已就绪
  if (hasLockFile() && isLockFileCompleted()) {
    return;
  }

  // 尝试原子地创建 lock 文件，确保只有一个进程能进入安装流程
  if (!tryCreateLockFile()) {
    // 其他进程正在安装，等待其完成
    await waitForCompletion(logger);
    // 等待结束后递归调用，检查环境是否已就绪或需要重试
    await initEnv(logger);
    return;
  }

  logger.info("开始初始化开发环境...");

  try {
    for (const { name, pkg } of GO_TOOLS) {
      try {
        logger.info(`安装 ${name}...`);
        const output = cmd.runSync("go", ["install", pkg], { env: { GOBIN: BIN_DIR } });
        output && logger.debug(output);
        logger.success(`${name} 安装成功`);
      } catch (error) {
        logger.error(`${name} 安装失败: ${(error as Error).message}`);
        throw error;
      }
    }

    // 标记安装完成
    completeLockFile();
    logger.success("环境初始化完成！");
  } catch (error) {
    // 安装失败时删除 lock 文件，允许后续重试
    removeLockFile();
    throw error;
  }
}

(async () => {
  if (import.meta.url === `file://${process.argv[1]}`) {
    await initEnv();
  }
})();

