name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.work
          cache-dependency-path: |
            apps/api/go.sum
            apps/backend/go.sum

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Initialize environment
        run: pnpm prepare

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
